from .pulizie import cancellaTestaLista
from .pulizie import pulisciFileFinale
from .pulizie import controlloProvincia
from .pulizie import controlloAbilitazione
from .pulizie import controlloLode
from .pulizie import controlloClasseLaurea
from .stampaFile import stampaFileRegistro
from .scomponiLista import scomponi
from .pergamena import pergamena
from .proceduraCamicie import creaCamicia
